# Generated by Django 5.2.4 on 2025-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('casts', models.ManyToManyField(related_name='movie_roles', to='moviesapp.cast')),
                ('categories', models.ManyToManyField(related_name='movies', to='moviesapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('casts', models.ManyToManyField(related_name='Series_roles', to='moviesapp.cast')),
                ('categories', models.ManyToManyField(related_name='Series', to='moviesapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
